"""
AegisSphere — Configuration Schemas and Data Models
====================================================
Strict Pydantic v2 schemas for the entire AegisSphere orchestration pipeline.
Every API request/response, tool call, and internal data structure is validated
through these models to enforce type safety and prevent untrusted data propagation.
"""

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, field_validator


# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------

class EscalationCode(str, Enum):
    """Severity codes for operational escalation."""
    GREEN = "GREEN"
    AMBER = "AMBER"
    RED = "RED"


class DIMICECategory(str, Enum):
    """
    DIM-ICE Framework categories for crowd incident classification.
    Design  — architectural / spatial flow constraints
    Information — signage, wayfinding, multilingual instruction gaps
    Management — staffing, steward deployment, operational control
    """
    DESIGN = "Design"
    INFORMATION = "Information"
    MANAGEMENT = "Management"


class IncidentPhase(str, Enum):
    """DIM-ICE movement phase where the bottleneck occurs."""
    INGRESS = "Ingress"
    CIRCULATION = "Circulation"
    EGRESS = "Egress"


class SecurityDesignation(str, Enum):
    """Federal / national security designation for the venue."""
    NSSE = "NSSE"  # US National Special Security Event
    CANADIAN_FEDERAL = "Canadian Federal Security"
    MEXICAN_FEDERAL = "Mexican Federal Security"


class TransportMode(str, Enum):
    """Available transport modes for transit routing."""
    RAIL = "Rail"
    BUS = "Bus"
    LIGHT_RAIL = "Light Rail"
    STREETCAR = "Streetcar"
    SHUTTLE = "Shuttle"
    RIDESHARE = "Rideshare"
    WALKING = "Walking"
    ACCESSIBLE_SHUTTLE = "Accessible Shuttle"


class SupplyCategory(str, Enum):
    """Supply chain item categories."""
    MERCHANDISE = "Merchandise"
    FOOD_BEVERAGE = "Food & Beverage"
    MEDICAL = "Medical Supplies"
    COLD_CHAIN = "Cold Chain"


# ---------------------------------------------------------------------------
# Crowd Safety Schemas
# ---------------------------------------------------------------------------

class CrowdMetrics(BaseModel):
    """Real-time crowd telemetry for a specific stadium zone."""
    density: float = Field(
        ...,
        ge=0,
        description="Calculated crowd density in persons per square meter (persons/m²)"
    )
    flow: float = Field(
        ...,
        ge=0,
        description="Calculated pedestrian flow rate in persons per meter per minute (persons/m/min)"
    )
    zone_id: str = Field(
        ...,
        min_length=1,
        description="Target stadium zone or concourse identifier"
    )
    venue_city: Optional[str] = Field(
        default=None,
        description="Host city name for venue-specific policy lookup"
    )


class EmergencyAction(BaseModel):
    """Structured remediation directive generated by the DIM-ICE framework."""
    action_type: DIMICECategory = Field(
        ...,
        description="Remediation category based on DIM-ICE classification"
    )
    phase: IncidentPhase = Field(
        default=IncidentPhase.CIRCULATION,
        description="Movement phase where intervention is applied"
    )
    dispatch_staff: bool = Field(
        ...,
        description="True if physical steward/security deployment is required"
    )
    broadcast_message: str = Field(
        ...,
        min_length=1,
        description="Dynamic, translated notification for localized digital signs and PA systems"
    )
    escalation_code: EscalationCode = Field(
        ...,
        description="Internal severity code (GREEN / AMBER / RED)"
    )
    reroute_zones: Optional[List[str]] = Field(
        default=None,
        description="List of zone IDs to redirect pedestrian flow towards"
    )


class OperationalResponse(BaseModel):
    """
    Unified response from the AegisSphere orchestration engine.
    Returned by the /v1/ops/evaluate endpoint.
    """
    incident_detected: bool = Field(
        ...,
        description="True if crowd safety thresholds are violated"
    )
    safety_analysis: str = Field(
        ...,
        description="Factual assessment of the current situation"
    )
    recommended_action: Optional[EmergencyAction] = Field(
        default=None,
        description="Structured action plan if incident is detected"
    )
    system_status: str = Field(
        default="NOMINAL",
        description="Overall system status indicator"
    )


# ---------------------------------------------------------------------------
# Transit & Accessibility Schemas
# ---------------------------------------------------------------------------

class TransitRequest(BaseModel):
    """Request for accessibility-aware transit routing."""
    origin: str = Field(..., description="Starting location or landmark")
    destination: str = Field(..., description="Target venue or zone")
    venue_city: str = Field(..., description="Host city name")
    require_step_free: bool = Field(
        default=False,
        description="If true, only return step-free accessible routes"
    )
    preferred_mode: Optional[TransportMode] = Field(
        default=None,
        description="Preferred transport mode filter"
    )
    language: str = Field(
        default="en",
        description="ISO 639-1 language code for response localization"
    )


class TransitStep(BaseModel):
    """A single step in a transit route."""
    mode: TransportMode
    instruction: str
    duration_minutes: float
    is_step_free: bool = True
    accessibility_notes: Optional[str] = None


class TransitResponse(BaseModel):
    """Response containing an optimized transit route."""
    route_id: str
    origin: str
    destination: str
    total_duration_minutes: float
    is_fully_accessible: bool
    carbon_score: float = Field(
        ...,
        ge=0,
        le=100,
        description="Green transport score (100 = zero carbon)"
    )
    steps: List[TransitStep]
    warnings: Optional[List[str]] = None


# ---------------------------------------------------------------------------
# Supply Chain Schemas
# ---------------------------------------------------------------------------

class SupplyChainItem(BaseModel):
    """An item in the supply chain monitoring pipeline."""
    item_id: str
    category: SupplyCategory
    current_stock: int = Field(..., ge=0)
    predicted_demand: int = Field(..., ge=0)
    reorder_threshold: int = Field(..., ge=0)
    venue_city: str


class ColdChainAlert(BaseModel):
    """Alert triggered when cold chain temperature thresholds are breached."""
    item_id: str
    current_temp_celsius: float
    max_safe_temp_celsius: float
    storage_unit_id: str
    venue_city: str
    alert_level: EscalationCode


class SupplyChainResponse(BaseModel):
    """Supply chain status response."""
    venue_city: str
    total_items_monitored: int
    items_below_reorder: List[SupplyChainItem] = []
    cold_chain_alerts: List[ColdChainAlert] = []
    replenishment_dispatched: bool = False
    system_status: str = "NOMINAL"


# ---------------------------------------------------------------------------
# Multilingual Schemas
# ---------------------------------------------------------------------------

class TranslationRequest(BaseModel):
    """Request for dynamic multilingual translation."""
    text: str = Field(..., min_length=1, description="Source text to translate")
    source_language: str = Field(default="en", description="ISO 639-1 source language code")
    target_language: str = Field(..., description="ISO 639-1 target language code")
    context: str = Field(
        default="stadium_operations",
        description="Translation context for domain-specific accuracy"
    )


class TranslationResponse(BaseModel):
    """Response containing translated text."""
    original_text: str
    translated_text: str
    source_language: str
    target_language: str
    html_lang_attribute: str = Field(
        ...,
        description="Value for HTML lang attribute (WCAG 3.1.2 compliance)"
    )


# ---------------------------------------------------------------------------
# Venue Profile Schemas
# ---------------------------------------------------------------------------

class VenueProfile(BaseModel):
    """Comprehensive operational profile for a host city venue."""
    city: str
    venue_name: str
    country: str
    matches_allocated: str
    transit_vulnerabilities: str
    climate_risks: str
    security_designation: SecurityDesignation
    security_funding: str
    key_operational_priority: str
    latitude: float
    longitude: float


# ---------------------------------------------------------------------------
# Guardrail Schemas
# ---------------------------------------------------------------------------

class GuardrailResult(BaseModel):
    """Result of input sanitization and security screening."""
    is_safe: bool = Field(..., description="True if input passed all security checks")
    threat_detected: Optional[str] = Field(
        default=None,
        description="Description of detected threat if input is unsafe"
    )
    sanitized_input: Optional[str] = Field(
        default=None,
        description="Cleaned input text if sanitization was applied"
    )
    processing_time_ms: float = Field(
        ...,
        ge=0,
        description="Time taken for guardrail processing in milliseconds"
    )


# ---------------------------------------------------------------------------
# Health Check Schema
# ---------------------------------------------------------------------------

class HealthResponse(BaseModel):
    """System health check response."""
    status: str = "healthy"
    version: str = "1.0.0"
    service: str = "AegisSphere Control Engine"
    active_venues: int = 16
